import Config

# Configure your database
config :scullion, Scullion.Repo,
  database: Path.expand("../scullion_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :scullion, ScullionWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "prDr/r0DTeXC10UBQFTbDA0FaIYa6D/5hwAENJIPSzn6sEcjl4uqRwN9pux/2wUf",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:scullion, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:scullion, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :scullion, ScullionWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/scullion_web/router\.ex$"E,
      ~r"lib/scullion_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

config :scullion, :http_client, Scullion.Adapters.ReqHTTP
config :scullion, :llm_client, Scullion.Adapters.OpenRouter
config :scullion, :image_gen_client, Scullion.Adapters.OpenRouter
config :scullion, :openrouter_api_key, System.get_env("OPENROUTER_API_KEY", "dev-key")
config :scullion, :openrouter_model, System.get_env("OPENROUTER_MODEL", "deepseek/deepseek-v4-flash")
config :scullion, :openrouter_vision_model, System.get_env("OPENROUTER_VISION_MODEL", "google/gemini-2.5-flash-lite")
config :scullion, :openrouter_image_model, System.get_env("OPENROUTER_IMAGE_MODEL", "google/gemini-2.5-flash-image")

# Enable dev routes for dashboard and mailbox
config :scullion, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
