import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :tore, ToreWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :tore, ToreWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

config :tore, :http_client, Tore.Adapters.ReqHTTP
config :tore, :llm_spec, Tore.LLM.OpenAI
config :tore, :image_gen_client, Tore.ImageGen.OpenRouter

# Do not print debug messages in production
config :logger, level: :info

# Initialize plugs at runtime so runtime.exs values (e.g. UPLOADS_DIR) are available
config :phoenix, :plug_init_mode, :runtime

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
